spring:
  application:
    name: cloudmusic
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/distribution_db?serverTimezone=Australia/Sydney
    username: root
    password: 123456
  jpa:
    hibernate:
      use-new-id-generator-mappings: false